"""
FiLM-conditioned UNet for conditional DDPM on ocean current fields.

Three conditioning modes are supported, selected by choosing cond_in_ch:

    cond_in_ch = 3  →  Voronoi conditioning
                        Channels: [u_voronoi, v_voronoi, sensor_mask]
                        Generated by nearest-neighbour tessellation from
                        biased-walk sensor positions.

    cond_in_ch = 1  →  Path conditioning
                        Channel: [path_mask]  (binary, 1 where robot walked)
                        Tells the model which cells were directly observed
                        without providing the measured values.

    cond_in_ch = 4  →  Both
                        Channels: [u_voronoi, v_voronoi, sensor_mask, path_mask]
                        Maximum information: interpolated field + path geometry.

FiLM (Feature-wise Linear Modulation)
--------------------------------------
Each FiLMResBlock receives a condition embedding (B, cond_dim) produced by a
shared CNN encoder. It predicts per-channel scale γ and shift β, then applies:

    h ← (1 + γ) ⊙ h + β          (residual FiLM)

Using (1 + γ) instead of γ means that γ = 0 at initialisation leaves
the activations unchanged, giving stable early training.

Reference: Perez et al., "FiLM: Visual Reasoning with a General Conditioning
Layer", AAAI 2018. https://arxiv.org/abs/1709.07871
"""

import math

import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def sinusoidal_embedding(t: torch.Tensor, dim: int) -> torch.Tensor:
    """Map integer timestep (B,) to sinusoidal embedding (B, dim)."""
    half = dim // 2
    freqs = torch.exp(
        -math.log(10000) * torch.arange(half, dtype=torch.float32, device=t.device) / (half - 1)
    )
    args = t.float()[:, None] * freqs[None]
    return torch.cat([args.sin(), args.cos()], dim=-1)


def _num_groups(channels: int) -> int:
    """Largest divisor of channels that is <= 32."""
    for g in [32, 16, 8, 4, 2, 1]:
        if channels % g == 0:
            return g
    return 1


# ---------------------------------------------------------------------------
# Condition encoder
# ---------------------------------------------------------------------------

class ConditionEncoder(nn.Module):
    """
    Lightweight CNN that maps a spatial condition map (B, cond_in_ch, H, W)
    to a fixed-size embedding vector (B, cond_dim).

    Uses strided convolutions followed by global average pooling, so it
    works for any input spatial resolution without hardcoding H and W.
    The output is consumed by all FiLMResBlocks in the UNet.
    """

    def __init__(self, in_ch: int, cond_dim: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, 32,  3, padding=1),
            nn.SiLU(),
            nn.Conv2d(32,  64,  3, stride=2, padding=1),   # H/2,  W/2
            nn.SiLU(),
            nn.Conv2d(64,  128, 3, stride=2, padding=1),   # H/4,  W/4
            nn.SiLU(),
            nn.Conv2d(128, 256, 3, stride=2, padding=1),   # H/8,  W/8
            nn.SiLU(),
            nn.AdaptiveAvgPool2d(1),                        # (B, 256, 1, 1)
            nn.Flatten(),                                   # (B, 256)
            nn.Linear(256, cond_dim),
            nn.SiLU(),
            nn.Linear(cond_dim, cond_dim),
        )

    def forward(self, cond: torch.Tensor) -> torch.Tensor:
        return self.net(cond)   # (B, cond_dim)


# ---------------------------------------------------------------------------
# FiLM residual block
# ---------------------------------------------------------------------------

class FiLMResBlock(nn.Module):
    """
    Residual block with two conditioning signals injected separately:

    1. Time embedding  →  additive shift after the first conv (same as the
                          base DDPM's ResBlock).
    2. Condition emb   →  FiLM: residual scale (1+γ) and shift β applied
                          after the time shift. γ and β are predicted by a
                          dedicated linear layer per block.

    The film_fc weight and bias are zero-initialised so that at the start of
    training the block behaves exactly like the unconditioned ResBlock.
    """

    def __init__(self, in_ch: int, out_ch: int, time_dim: int, cond_dim: int):
        super().__init__()
        self.norm1   = nn.GroupNorm(_num_groups(in_ch),  in_ch)
        self.conv1   = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.time_fc = nn.Linear(time_dim, out_ch)
        self.film_fc = nn.Linear(cond_dim, out_ch * 2)    # → (γ, β) concatenated
        self.norm2   = nn.GroupNorm(_num_groups(out_ch), out_ch)
        self.conv2   = nn.Conv2d(out_ch, out_ch, 3, padding=1)
        self.skip    = nn.Conv2d(in_ch, out_ch, 1) if in_ch != out_ch else nn.Identity()
        self.act     = nn.SiLU()

        # Zero-init FiLM projection: γ=0, β=0 → identity at init
        nn.init.zeros_(self.film_fc.weight)
        nn.init.zeros_(self.film_fc.bias)

    def forward(
        self,
        x:        torch.Tensor,   # (B, in_ch, H, W)
        t_emb:    torch.Tensor,   # (B, time_dim)
        cond_emb: torch.Tensor,   # (B, cond_dim)
    ) -> torch.Tensor:
        h = self.act(self.norm1(x))
        h = self.conv1(h)

        # Time shift (additive, same as base DDPM)
        h = h + self.time_fc(self.act(t_emb))[:, :, None, None]

        # FiLM: residual scale + shift from condition
        gamma, beta = self.film_fc(self.act(cond_emb)).chunk(2, dim=1)
        h = (1.0 + gamma[:, :, None, None]) * h + beta[:, :, None, None]

        h = self.act(self.norm2(h))
        h = self.conv2(h)
        return h + self.skip(x)


# ---------------------------------------------------------------------------
# FiLM-conditioned UNet
# ---------------------------------------------------------------------------

class CondUNet(nn.Module):
    """
    2D UNet for FiLM-conditioned DDPM noise prediction on ocean current fields.

    Identical encoder-decoder architecture to the base UNet, but every
    ResBlock is replaced with FiLMResBlock and a ConditionEncoder produces
    the conditioning embedding from the spatial condition map.

    Input spatial size: (H, W) = (94, 44).
    Internally padded to (96, 48) for clean 2× downsampling.

    Args:
        in_ch:      channels of the noisy field (default: 2 for u, v).
        cond_in_ch: channels of the conditioning map:
                      3 = Voronoi   [u_vor, v_vor, sensor_mask]
                      1 = path mask [path_mask]
                      4 = both      [u_vor, v_vor, sensor_mask, path_mask]
        base_ch:    base channel width of the UNet (default: 64).
        time_dim:   sinusoidal time embedding dimension (default: 256).
        cond_dim:   dimension of the encoded condition embedding (default: 256).
    """

    # F.pad convention: (left, right, top, bottom) for last two dims
    _PAD = (2, 2, 1, 1)   # W: 44 → 48,  H: 94 → 96

    def __init__(
        self,
        in_ch:      int = 2,
        cond_in_ch: int = 3,
        base_ch:    int = 64,
        time_dim:   int = 256,
        cond_dim:   int = 256,
    ):
        super().__init__()
        self.time_dim = time_dim
        c = base_ch

        self.time_mlp = nn.Sequential(
            nn.Linear(time_dim, time_dim * 4),
            nn.SiLU(),
            nn.Linear(time_dim * 4, time_dim),
        )

        self.cond_encoder = ConditionEncoder(cond_in_ch, cond_dim)

        # Encoder
        self.enc0 = FiLMResBlock(in_ch,   c,    time_dim, cond_dim)   # 96×48
        self.enc1 = FiLMResBlock(c,       c*2,  time_dim, cond_dim)   # 48×24
        self.enc2 = FiLMResBlock(c*2,     c*4,  time_dim, cond_dim)   # 24×12
        self.enc3 = FiLMResBlock(c*4,     c*8,  time_dim, cond_dim)   # 12×6

        # Bottleneck
        self.mid  = FiLMResBlock(c*8,     c*8,  time_dim, cond_dim)   # 6×3

        # Decoder  (skip connections double the input channels)
        self.dec3 = FiLMResBlock(c*8+c*8, c*4,  time_dim, cond_dim)   # 12×6
        self.dec2 = FiLMResBlock(c*4+c*4, c*2,  time_dim, cond_dim)   # 24×12
        self.dec1 = FiLMResBlock(c*2+c*2, c,    time_dim, cond_dim)   # 48×24
        self.dec0 = FiLMResBlock(c  +c,   c,    time_dim, cond_dim)   # 96×48

        self.out_conv = nn.Conv2d(c, in_ch, 1)

        self.down = nn.MaxPool2d(2)
        self.up   = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False)

    def forward(
        self,
        x:    torch.Tensor,   # (B, 2, 94, 44)  noisy field
        t:    torch.Tensor,   # (B,)             integer timesteps
        cond: torch.Tensor,   # (B, cond_in_ch, H, W)  conditioning map
    ) -> torch.Tensor:
        """
        Returns predicted noise: (B, 2, 94, 44).
        """
        # Pad noisy input to 96×48
        x = F.pad(x, self._PAD)

        # Time and condition embeddings
        t_emb    = sinusoidal_embedding(t, self.time_dim)
        t_emb    = self.time_mlp(t_emb)      # (B, time_dim)
        cond_emb = self.cond_encoder(cond)    # (B, cond_dim) — no padding needed

        # Encoder
        e0 = self.enc0(x,              t_emb, cond_emb)   # 96×48
        e1 = self.enc1(self.down(e0),  t_emb, cond_emb)   # 48×24
        e2 = self.enc2(self.down(e1),  t_emb, cond_emb)   # 24×12
        e3 = self.enc3(self.down(e2),  t_emb, cond_emb)   # 12×6

        # Bottleneck
        h = self.mid(self.down(e3), t_emb, cond_emb)      # 6×3

        # Decoder with skip connections
        h = self.up(h)
        h = self.dec3(torch.cat([h, e3], dim=1), t_emb, cond_emb)   # 12×6

        h = self.up(h)
        h = self.dec2(torch.cat([h, e2], dim=1), t_emb, cond_emb)   # 24×12

        h = self.up(h)
        h = self.dec1(torch.cat([h, e1], dim=1), t_emb, cond_emb)   # 48×24

        h = self.up(h)
        h = self.dec0(torch.cat([h, e0], dim=1), t_emb, cond_emb)   # 96×48

        h = self.out_conv(h)

        # Unpad: strip top=1, bottom=1 from H and left=2, right=2 from W
        h = h[:, :, 1:-1, 2:-2]   # → (B, 2, 94, 44)
        return h
