"""
noise_types.py – Colored Gaussian noise for 2-D vector-field DDPMs.

Theory
------
Colored (spatially correlated) Gaussian noise is generated by filtering
white Gaussian noise in the Fourier domain.  For a target power spectrum
proportional to |f|^{-alpha}:

    1. Sample white noise  z ~ N(0, I)  of shape (B, C, H, W).
    2. Compute 2-D real FFT:   Z = rfft2(z).
    3. Build spectral weight:  W(f) = (|f|^2 + eps)^{-alpha/2}.
    4. Multiply:               Z_c = Z * W.
    5. Invert:                 noise = irfft2(Z_c).
    6. Normalize each (b, c) slice to zero mean, unit std.

Spectral exponent alpha controls spatial smoothness:
  alpha = 0  →  white noise (no correlation; equivalent to torch.randn)
  alpha = 1  →  pink noise (1/f power spectrum)
  alpha = 2  →  red / Brownian noise (smooth, large-scale correlations)

For ocean current fields, alpha ≈ 2 matches the roughly k^{-2} energy
spectrum of mesoscale ocean turbulence and is the recommended default.
"""

import math
import torch
import torch.fft


def colored_gaussian_noise(
    shape: tuple,
    alpha: float = 2.0,
    device: "torch.device | str" = "cpu",
) -> torch.Tensor:
    """Generate a batch of spatially correlated (colored) Gaussian noise.

    Parameters
    ----------
    shape : (B, C, H, W)
        Desired output shape.
    alpha : float
        Spectral exponent.  0 = white, 1 = pink, 2 = red/Brownian.
        Values in [1, 3] are typical for geophysical fields.
    device : str or torch.device
        Target device.

    Returns
    -------
    noise : FloatTensor of shape (B, C, H, W)
        Zero mean, unit std per (b, c) slice; spatially correlated.
    """
    B, C, H, W = shape

    # --- white noise ---
    noise = torch.randn(B, C, H, W, device=device)

    if alpha == 0.0:
        return noise

    # --- Fourier domain ---
    # rfft2 returns complex tensor of shape (B, C, H, W//2+1)
    noise_fft = torch.fft.rfft2(noise, norm="ortho")

    # --- spectral weight: W(f) = (|f|^2 + eps)^{-alpha/2} ---
    freq_h = torch.fft.fftfreq(H, device=device)        # (H,)
    freq_w = torch.fft.rfftfreq(W, device=device)       # (W//2+1,)
    fh, fw = torch.meshgrid(freq_h, freq_w, indexing="ij")  # (H, W//2+1)

    f_sq = fh ** 2 + fw ** 2                            # (H, W//2+1)
    eps  = 1e-10                                        # avoid DC = inf
    spectral_weight = (f_sq + eps) ** (-alpha / 2.0)   # (H, W//2+1)

    # broadcast over batch and channel dimensions
    noise_fft = noise_fft * spectral_weight[None, None]

    # --- back to spatial domain ---
    filtered = torch.fft.irfft2(noise_fft, s=(H, W), norm="ortho")  # (B, C, H, W)

    # --- normalize each (b, c) slice to zero mean, unit std ---
    mean = filtered.mean(dim=(-2, -1), keepdim=True)
    std  = filtered.std(dim=(-2, -1), keepdim=True).clamp(min=1e-8)
    filtered = (filtered - mean) / std

    return filtered
